import 'dotenv/config';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  slYears,
  secondLeagueAge,
  secondLeagueClubRanking,
  secondLeagueMatchVideo,
  secondLeagueMatchProtocol,
  isSecondLeagueConfigured,
  isBigbroConfigured,
  type SlAgeData,
  type SlClubRow,
} from '../federation/secondLeague.js';

// Простой пул параллелизма (щадим FFSPB).
async function pmap<T>(items: T[], limit: number, fn: (x: T) => Promise<void>): Promise<void> {
  let i = 0;
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (i < items.length) { const k = i++; await fn(items[k]!); }
  }));
}

/**
 * SYNC Второй лиги (ФФСПб) в статический снимок: запускать ЛОКАЛЬНО/где есть доступ
 * к stat.ffspb.org + api.bigbro.ai (с Render — IP-блок/тормоза прокси, поэтому живой
 * фетч в запросе не годится). Тянет по каждому возрасту таблицу+календарь, клубный
 * зачёт и ССЫЛКИ НА ВИДЕО (Big Bro origin-mp4) — пишет готовый снимок в
 * src/federation/secondLeague.generated.ts. Бэкенд отдаёт его мгновенно, без живого
 * FFSPB/BigBro. Обновление: npm run sync:secondleague.
 */

interface VideoParts { status: string | null; name: string | null; parts: string[] }
interface Snapshot {
  generatedAt: string;
  years: number[];
  ages: Record<number, SlAgeData>;
  clubRanking: { years: number[]; ranking: SlClubRow[] };
  videos: Record<string, VideoParts>;
}

async function main() {
  if (!isSecondLeagueConfigured()) { console.error('FFSPB_API_KEY не задан в .env'); process.exit(1); }
  const bb = isBigbroConfigured();
  console.log(`sync Второй лиги · Big Bro креды: ${bb ? 'есть' : 'НЕТ (видео не соберётся)'}`);

  const years = slYears();
  const ages: Record<number, SlAgeData> = {};
  const slugs = new Set<string>();

  for (const y of years) {
    const age = await secondLeagueAge(y);
    if (!age) { console.log(`  ${y}: пусто, пропуск`); continue; }
    ages[y] = age;
    let vids = 0;
    for (const m of age.matches) if (m.videoSlug) { slugs.add(m.videoSlug); vids++; }
    console.log(`  ${y} (${age.age}): матчей ${age.matches.length}, таблица ${age.table.length}, привязок видео ${vids}`);
  }

  // Пре-синк протокола (голы/карточки/замены) по сыгранным матчам — для модалки.
  const playedMatches = years.flatMap((y) => ages[y]?.matches.filter((m) => m.played) ?? []);
  console.log(`  протокол по ${playedMatches.length} сыгранным матчам…`);
  let prOk = 0;
  await pmap(playedMatches, 6, async (m) => {
    try {
      m.protocol = await secondLeagueMatchProtocol(m.id);
      if (m.protocol.goals.length || m.protocol.cards.length || m.protocol.subs.length) prOk++;
    } catch { m.protocol = null; }
  });
  console.log(`  протокол собран: ${prOk}/${playedMatches.length} с событиями`);

  console.log('  клубный зачёт…');
  const clubRanking = await secondLeagueClubRanking();
  console.log(`  зачёт: клубов ${clubRanking.ranking.length}`);

  // Пре-синк прямых ссылок на видео (origin-mp4) по каждому slug — чтобы Render
  // не ходил в Big Bro в запросе (там IP-блок/зависание).
  const videos: Record<string, VideoParts> = {};
  if (bb && slugs.size) {
    console.log(`  видео-ссылки по ${slugs.size} матчам…`);
    let ok = 0;
    for (const slug of slugs) {
      try {
        const v = await secondLeagueMatchVideo(slug);
        if (v.parts.length) { videos[slug] = v; ok++; }
      } catch { /* пропуск */ }
    }
    console.log(`  видео собрано: ${ok}/${slugs.size}`);
  }

  const data: Snapshot = {
    generatedAt: new Date().toISOString(),
    years,
    ages,
    clubRanking,
    videos,
  };

  const out = resolve(import.meta.dirname, '../federation/secondLeague.generated.ts');
  const body = `// AUTO-GENERATED by scripts/syncSecondLeague.ts — НЕ РЕДАКТИРОВАТЬ вручную.
// Снимок Второй лиги (ФФСПб): календарь+таблица+зачёт+ссылки на видео. Бэкенд отдаёт
// мгновенно, без живого FFSPB/BigBro (Render заблокён по IP / прокси тормозит).
// Обновить: npm run sync:secondleague (нужен доступ к stat.ffspb.org + api.bigbro.ai + креды в .env).
import type { SlAgeData, SlClubRow } from './secondLeague.js';

export interface SlVideoParts { status: string | null; name: string | null; parts: string[] }
export interface SecondLeagueSnapshot {
  generatedAt: string;
  years: number[];
  ages: Record<number, SlAgeData>;
  clubRanking: { years: number[]; ranking: SlClubRow[] };
  videos: Record<string, SlVideoParts>;
}

export const SECOND_LEAGUE: SecondLeagueSnapshot = ${JSON.stringify(data, null, 2)};
`;
  writeFileSync(out, body, 'utf8');
  console.log(`\n✓ записано ${out}`);
  console.log(`итог: возрастов ${Object.keys(ages).length}, клубов в зачёте ${clubRanking.ranking.length}, видео ${Object.keys(videos).length}`);
}

main().then(() => process.exit(0)).catch((e) => { console.error('ERR:', e?.message || e); process.exit(1); });
