// AUTO-GENERATED by scripts/syncLossMap.ts — НЕ РЕДАКТИРОВАТЬ вручную.
// Обновить: npm run sync:lossmap (нужен доступ к stat.ffspb.org + FFSPB_API_KEY).

export interface LossQuarter { q: number; roster: number; medianPct: number; buried15: number; buried30: number; contrib50: number }
export interface LossCohort { year: number; label: string; roster: number; byQuarter: LossQuarter[] }
export interface LossMap {
  generatedAt: string; season: number; note: string;
  pooled: { roster: number; byQuarter: LossQuarter[] };
  cohorts: LossCohort[];
  examplesBuriedQ4: Array<{ name: string; team: string; pct: number; year: number }>;
}

export const LOSS_MAP: LossMap = {
  "generatedAt": "2026-06-19T12:22:31.917Z",
  "season": 2,
  "note": "% времени = минуты игрока / доступные минуты его команды; реестр = заявка (FFSPB /players?team=)",
  "pooled": {
    "roster": 1872,
    "byQuarter": [
      {
        "q": 1,
        "roster": 671,
        "medianPct": 43,
        "buried15": 29,
        "buried30": 40,
        "contrib50": 45
      },
      {
        "q": 2,
        "roster": 515,
        "medianPct": 43,
        "buried15": 31,
        "buried30": 40,
        "contrib50": 44
      },
      {
        "q": 3,
        "roster": 431,
        "medianPct": 45,
        "buried15": 28,
        "buried30": 38,
        "contrib50": 47
      },
      {
        "q": 4,
        "roster": 255,
        "medianPct": 33,
        "buried15": 36,
        "buried30": 48,
        "contrib50": 40
      }
    ]
  },
  "cohorts": [
    {
      "year": 2013,
      "label": "U-13",
      "roster": 383,
      "byQuarter": [
        {
          "q": 1,
          "roster": 134,
          "medianPct": 48,
          "buried15": 26,
          "buried30": 36,
          "contrib50": 47
        },
        {
          "q": 2,
          "roster": 109,
          "medianPct": 48,
          "buried15": 29,
          "buried30": 37,
          "contrib50": 45
        },
        {
          "q": 3,
          "roster": 93,
          "medianPct": 45,
          "buried15": 30,
          "buried30": 41,
          "contrib50": 45
        },
        {
          "q": 4,
          "roster": 47,
          "medianPct": 42,
          "buried15": 32,
          "buried30": 43,
          "contrib50": 45
        }
      ]
    },
    {
      "year": 2012,
      "label": "U-14",
      "roster": 392,
      "byQuarter": [
        {
          "q": 1,
          "roster": 138,
          "medianPct": 47,
          "buried15": 32,
          "buried30": 39,
          "contrib50": 46
        },
        {
          "q": 2,
          "roster": 123,
          "medianPct": 39,
          "buried15": 35,
          "buried30": 44,
          "contrib50": 45
        },
        {
          "q": 3,
          "roster": 77,
          "medianPct": 44,
          "buried15": 31,
          "buried30": 36,
          "contrib50": 47
        },
        {
          "q": 4,
          "roster": 54,
          "medianPct": 25,
          "buried15": 43,
          "buried30": 54,
          "contrib50": 37
        }
      ]
    },
    {
      "year": 2011,
      "label": "U-15",
      "roster": 385,
      "byQuarter": [
        {
          "q": 1,
          "roster": 153,
          "medianPct": 38,
          "buried15": 33,
          "buried30": 43,
          "contrib50": 41
        },
        {
          "q": 2,
          "roster": 90,
          "medianPct": 38,
          "buried15": 33,
          "buried30": 42,
          "contrib50": 39
        },
        {
          "q": 3,
          "roster": 89,
          "medianPct": 50,
          "buried15": 20,
          "buried30": 30,
          "contrib50": 52
        },
        {
          "q": 4,
          "roster": 53,
          "medianPct": 35,
          "buried15": 40,
          "buried30": 49,
          "contrib50": 43
        }
      ]
    },
    {
      "year": 2010,
      "label": "U-16",
      "roster": 376,
      "byQuarter": [
        {
          "q": 1,
          "roster": 134,
          "medianPct": 44,
          "buried15": 23,
          "buried30": 39,
          "contrib50": 45
        },
        {
          "q": 2,
          "roster": 104,
          "medianPct": 44,
          "buried15": 29,
          "buried30": 37,
          "contrib50": 44
        },
        {
          "q": 3,
          "roster": 82,
          "medianPct": 43,
          "buried15": 27,
          "buried30": 37,
          "contrib50": 46
        },
        {
          "q": 4,
          "roster": 56,
          "medianPct": 33,
          "buried15": 38,
          "buried30": 46,
          "contrib50": 38
        }
      ]
    },
    {
      "year": 2009,
      "label": "U-17",
      "roster": 336,
      "byQuarter": [
        {
          "q": 1,
          "roster": 112,
          "medianPct": 48,
          "buried15": 31,
          "buried30": 42,
          "contrib50": 49
        },
        {
          "q": 2,
          "roster": 89,
          "medianPct": 49,
          "buried15": 28,
          "buried30": 38,
          "contrib50": 49
        },
        {
          "q": 3,
          "roster": 90,
          "medianPct": 39,
          "buried15": 31,
          "buried30": 43,
          "contrib50": 43
        },
        {
          "q": 4,
          "roster": 45,
          "medianPct": 32,
          "buried15": 24,
          "buried30": 49,
          "contrib50": 40
        }
      ]
    }
  ],
  "examplesBuriedQ4": [
    {
      "name": "Танев-Дубских Савватий",
      "team": "Зенит",
      "pct": 0,
      "year": 2009
    },
    {
      "name": "Седойкин Матвей",
      "team": "ФК Динамо-СПб",
      "pct": 0,
      "year": 2009
    },
    {
      "name": "Хомец Фёдор",
      "team": "Ижорец",
      "pct": 0,
      "year": 2009
    },
    {
      "name": "Синицын Данила",
      "team": "Зенит",
      "pct": 0,
      "year": 2010
    },
    {
      "name": "Соколов Владислав",
      "team": "Зенит",
      "pct": 0,
      "year": 2010
    },
    {
      "name": "Лихачёв Матвей",
      "team": "Царское Село-Динамо ",
      "pct": 0,
      "year": 2010
    },
    {
      "name": "Щиров Глеб",
      "team": "Царское Село-Динамо ",
      "pct": 0,
      "year": 2010
    },
    {
      "name": "Нуриддинов Бехруз",
      "team": "Автово",
      "pct": 0,
      "year": 2010
    }
  ]
};
